export const skillsData = [
    "Html",
    "Css",
    "Vercel",
    "TypeScript",
    "React",
    "Next.js",
    "Node.js",
    "Git",
    "Tailwind",
    "Java",
    "Springboot",
    "Discord",
    "Slack",
    "VSCode",
    "Intellij",
    "Command Line",
    "Npm",
    "PostgreSQL",
    "APIs",
    "Postman",
    "Python",
    "Flask",
    "Solidity",
    "Web3.js/Ethers.js"
  ] as const;